name: Gtb test all
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: |
          ./gradlew clean build test
      - if: ${{ success() }}
        run: echo "TEST_RESULT=true" >> $GITHUB_ENV
      - if: ${{ failure() }}
        run: echo "TEST_RESULT=false" >> $GITHUB_ENV
      - if: ${{ always() }}
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)
          curl -X POST "${{ secrets.DASHBOARD_ADDRESS }}/terms/${{ secrets.STUDENT_TERM }}/submissions/test?assignmentKey=${PROJECT_NAME}&gtbUsername=${{ secrets.STUDENT_NAME }}" \
              -H "Content-Type: application/json" \
              -u user:${{ secrets.SONAR_TOKEN }} \
              -d "${TEST_RESULT}"

